apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdlc-ingress
spec:
  rules:
  - host: vscode.sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8084
  - host: syson.sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8081
  - host: penpot.sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8080
  - host: opencode.sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8083
  - host: terminal.sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8085
  - host: sdlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdlc-service
            port:
              number: 8083
